lint: {}
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: "@CaroAMN"
  description: pipeline for processing and integration of MACSima multiplexed imaging
    with H&E stained tissue slides
  force: false
  is_nfcore: true
  name: spatiallattice
  org: nf-core
  outdir: .
  version: 1.0.0dev
